version: '3.7'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - external
  nginx:
    build: ./build/docker/nginx/laravel
    image: example/nginx:1.0.0
    networks:
      - external
      - php
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=testing.ben.local
    depends_on:
      - nginx-proxy
      - php
    volumes:
      - ./:/var/www/html:delegated
  php:
    build: ./build/docker/php
    image: example/php:1.0.0
    networks:
      - php
      - cache
      - database
    depends_on:
      - database
      - cache
    volumes:
      - ./:/var/www/html:delegated
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
  node:
    image: node:8.11.4-alpine
    depends_on:
      - php
    volumes:
      - ./:/var/www/html:delegated
    working_dir: /var/www/html
    command: ['npm', 'run', 'watch']
  database:
    image: postgres:10-alpine
    networks:
      - database
    volumes:
      - pgsql:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER:  ${DB_USERNAME}
      POSTGRES_DB:  ${DB_DATABASE}
  cache:
    image: redis:alpine
    networks:
      - cache
    volumes:
      - redis:/data
networks:
  external:
  php:
  cache:
  database:
volumes:
  pgsql:
  redis:
