version: '3.7'

services:
  nginx:
    image: nginx:1.17.5-alpine
    restart: on-failure
    init: true
    networks:
      - external
      - php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./scripts/nginx/conf.d/:/etc/nginx/conf.d/:cached
  php:
    build:
      context: ./scripts/dockerfiles/php/
      target: development
      dockerfile: Dockerfile-73
    image: image-naame/php:1.0.0
    init: true
    networks:
      - php
      - cache
    depends_on:
      - nginx
      - redis
    volumes:
      - ./:/var/www/html:delegated
    # Add this key with a value of 1 to .env to enable xdebug
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
      - PHP_IDE_CONFIG=serverName=my.local.site
      - XDEBUG_CONFIG=idekey=docker

  redis:
    image: redis:alpine
    init: true
    networks:
      - cache

networks:
  external:
  php:
  cache:
