version: '3.1'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - appnet
  nginx:
    image: benfreke/nginx-laravel:0.0.1
    ports:
     - "80"
     - "443"
    volumes:
     - ./app:/var/www/html
    networks:
     - appnet
    depends_on:
     - php
    environment:
     - VIRTUAL_HOST=laravel.dev
  php:
    image: benfreke/php7.1-laravel:0.0.1
    volumes:
     - ./app:/var/www/html
    networks:
     - appnet
  redis:
    image: redis:3.0-alpine
    networks:
     - appnet
  db-postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: homestead
      POSTGRES_DB: homestead
    volumes:
     - data:/var/lib/postgresql/data
    networks:
     - appnet
    ports:
     - "5432"
  db-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"